# Generated by Django 5.2.5 on 2025-08-16 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address - must be unique", max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number in format +1234567890 or 123-456-7890', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+1234567890' or '123-456-7890'", regex='^(\\+\\d{1,3}[-.]?)?\\(?\\d{3}\\)?[-.]?\\d{3}[-.]?\\d{4}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this customer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this customer was last updated')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price - must be positive', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of items in stock - cannot be negative')),
                ('description', models.TextField(blank=True, help_text='Optional product description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this product was last updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='When this order was placed')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for this order (calculated from product prices)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this order record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this order was last updated')),
                ('customer', models.ForeignKey(help_text='Customer who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer')),
                ('products', models.ManyToManyField(help_text='Products included in this order', related_name='orders', to='crm.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
